### ISSUE TITLE
Snowflake: Cannot login via Import Process

### ISSUE THREAD

**Issue by markddrake** [markddrake/YADAMU---Yet-Another-DAta-Migration-Utility#34]
```
C:\Development\YADAMU>bin\import rdbms=snowflake username=mdrake account=yabasc_partner warehouse=DEMO_WH database="ORACLE" TO_USER="HR" file=hr.exp
Enter password for SNOWFLAKE connection: **********
2021-01-24T19:47:59.839Z [INFO][Reader][FILE][N/A][DATA_ONLY][Manager]: Ready.
2021-01-24T19:47:59.842Z [INFO][Writer][SNOWFLAKE][5.1.2][DATA_ONLY][Manager]: Ready.
2021-01-24T19:47:59.990Z [ERROR][YADAMU][IMPORT]: Operation Failed:
SnowflakeError: SQL compilation error:
Database '"undefined"' does not exist or not authorized.
    at C:\Development\YADAMU\src\YADAMU\snowflake\node\snowflakeDBI.js:147:18
    at new Promise (<anonymous>)
    at SnowflakeDBI.executeSQL (C:\Development\YADAMU\src\YADAMU\snowflake\node\snowflakeDBI.js:143:12)
    at SnowflakeDBI.getSchemaInfo (C:\Development\YADAMU\src\YADAMU\snowflake\node\snowflakeDBI.js:411:30)
    at DBWriter.getTargetSchemaInfo (C:\Development\YADAMU\src\YADAMU\common\dbWriter.js:115:39)
    at DBWriter.initialize (C:\Development\YADAMU\src\YADAMU\common\dbWriter.js:211:37)
    at async Yadamu.getDBWriter (C:\Development\YADAMU\src\YADAMU\common\yadamu.js:563:5)
    at async Yadamu.doPumpOperation (C:\Development\YADAMU\src\YADAMU\common\yadamu.js:583:24)
    at async Yadamu.pumpData (C:\Development\YADAMU\src\YADAMU\common\yadamu.js:650:12)
    at async Yadamu.doImport (C:\Development\YADAMU\src\YADAMU\common\yadamu.js:655:21) {
  cause: Error [OperationFailedError]: SQL compilation error:
  Database '"undefined"' does not exist or not authorized.
      at createError (C:\Development\YADAMU\src\node_modules\snowflake-sdk\lib\errors.js:525:15)
      at Object.exports.createOperationFailedError (C:\Development\YADAMU\src\node_modules\snowflake-sdk\lib\errors.js:304:10)
      at Object.callback (C:\Development\YADAMU\src\node_modules\snowflake-sdk\lib\services\sf.js:624:28)
      at Request._callback (C:\Development\YADAMU\src\node_modules\snowflake-sdk\lib\http\base.js:107:19)
      at Request.self.callback (C:\Development\YADAMU\src\node_modules\request\request.js:185:22)
      at Request.emit (events.js:315:20)
      at Request.<anonymous> (C:\Development\YADAMU\src\node_modules\request\request.js:1154:10)
      at Request.emit (events.js:315:20)
      at IncomingMessage.<anonymous> (C:\Development\YADAMU\src\node_modules\request\request.js:1076:12)
      at Object.onceWrapper (events.js:421:28) {
    code: '002003',
    sqlState: '02000',
    data: {
      internalError: false,
      errorCode: '002003',
      age: 0,
      sqlState: '02000',
      queryId: '0199d484-0467-1632-000d-54830044e07e',
      line: 30,
      pos: 22,
      type: 'COMPILATION'
    }
  },
  sql: 'select t.table_schema   "TABLE_SCHEMA"\n' +
    '                     ,t.table_name   "TABLE_NAME"\n' +
    `                     ,concat('[',listagg(concat('"',c.column_name,'"'),',') within group (order by ordinal_position),']') "COLUMN_NAME_ARRAY"\n` +
    `                     ,concat('[',listagg(concat('"',data_type,'"'),',') within group (order by ordinal_position),']') "DATA_TYPE_ARRAY"\n` +
    "                     ,concat('[',listagg(case\n" +
    '                                   when (numeric_precision is not null) and (numeric_scale is not null) \n' +
    `                                     then concat('"',numeric_precision,',',numeric_scale,'"')\n` +
    '                                   when (numeric_precision is not null) \n' +
    `                                     then concat('"',numeric_precision,'"')\n` +
    '                                   when (datetime_precision is not null)\n' +
    `                                     then concat('"',datetime_precision,'"')\n` +
    '                                   when (character_maximum_length is not null)\n' +
    `                                     then concat('"',character_maximum_length,'"')\n` +
    '                                   else\n' +
    `                                     '""'\n` +
    '                                 end\n' +
    "                                ,','                   \n" +
    '                               ) within group (order by ordinal_position)\n' +
    `                             ,']') "SIZE_CONSTRAINT_ARRAY"\n` +
    '                     ,listagg(case\n' +
    "                               when c.data_type = 'VARIANT' then\n" +
    `                                 concat('TO_VARCHAR("',column_name,'") "',column_name,'"')\n` +
    "                               when c.data_type = 'TIME' then\n" +
    `                                 concat('cast(concat(''1971-01-01T'',','"',column_name,'"',') as Timestamp)')\n` +
    '                               else\n' +
    `                                 concat('"',column_name,'"')\n` +
    '                               end\n' +
    "                              ,','\n" +
    '                             ) within group (order by ordinal_position) "CLIENT_SELECT_LIST"\n' +
    '                 from "undefined"."INFORMATION_SCHEMA"."COLUMNS" c, "undefined"."INFORMATION_SCHEMA"."TABLES" t\n' +
    '                where t.table_name = c.table_name\n' +
    '                  and t.table_schema = c.table_schema\n' +
    "                  and t.table_type = 'BASE TABLE'\n" +
    '                  and t.table_schema = ?\n' +
    '                group by t.table_schema, t.table_name'
}
2021-01-24T19:48:00.008Z [INFO][YADAMU][IMPORT]: Operation complete: File:"hr.exp". Elapsed Time: 00:00:04.947s.
```

**Comment by markddrake** [comment]
Check whether not the property this.parameters.YADAMU_DATABASE is defined in getConnectionProperties(). If it is not defined set it to the value of this.parameter.DATABASE
