### ISSUE TITLE
MsSQLDBI: Duplicate Column Binding error when inserting row with JSON and Spatial columns

### ISSUE THREAD

**Issue by markddrake** [markddrake/YADAMU---Yet-Another-DAta-Migration-Utility#59]
If a table has a (logical) JSON column and a Spatial (Geometry Column) then a duplicate parameter name error is reported when attempting to prepare the SQL statement  required for the the insert operation.
```
2021-02-08T01:24:07.516Z [ERROR][MSSQLSERVER][INSERT ONE]["airports_data"]: The parameter name C1 has already been declared. Parameter names must be unique
MsSQLError: The parameter name C1 has already been declared. Parameter names must be unique
    at MsSQLDBI.getPreparedStatement (C:\Development\YADAMU\src\YADAMU\mssql\node\mssqlDBI.js:214:15)
    at MsSQLDBI.cachePreparedStatement (C:\Development\YADAMU\src\YADAMU\mssql\node\mssqlDBI.js:590:35)
    at MsSQLWriter._writeBatch (C:\Development\YADAMU\src\YADAMU\mssql\node\mssqlWriter.js:151:22)
    at MsSQLWriter.processBatch (C:\Development\YADAMU\src\YADAMU\common\yadamuWriter.js:355:34)
    at MsSQLWriter.finalize (C:\Development\YADAMU\src\YADAMU\common\yadamuWriter.js:629:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async MsSQLWriter.finalize (C:\Development\YADAMU\src\YADAMU\mssql\node\mssqlWriter.js:190:2)
    at async MsSQLWriter._destroy (C:\Development\YADAMU\src\YADAMU\common\yadamuWriter.js:677:7) {
  cause: PreparedStatementError: The parameter name C1 has already been declared. Parameter names must be unique
      at PreparedStatement.input (C:\Development\YADAMU\src\node_modules\mssql\lib\base\prepared-statement.js:103:13)
      at C:\Development\YADAMU\src\YADAMU\mssql\node\mssqlDBI.js:279:23
      at Array.forEach (<anonymous>)
      at MsSQLDBI.getPreparedStatement (C:\Development\YADAMU\src\YADAMU\mssql\node\mssqlDBI.js:216:17)
      at MsSQLDBI.cachePreparedStatement (C:\Development\YADAMU\src\YADAMU\mssql\node\mssqlDBI.js:590:35)
      at MsSQLWriter._writeBatch (C:\Development\YADAMU\src\YADAMU\mssql\node\mssqlWriter.js:151:22)
      at MsSQLWriter.processBatch (C:\Development\YADAMU\src\YADAMU\common\yadamuWriter.js:355:34)
      at MsSQLWriter.finalize (C:\Development\YADAMU\src\YADAMU\common\yadamuWriter.js:629:9)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async MsSQLWriter.finalize (C:\Development\YADAMU\src\YADAMU\mssql\node\mssqlWriter.js:190:2) {
    code: 'EDUPEPARAM'
  },
  sql: 'sql.PreparedStatement(insert into "dbo"."airports_data" ("airport_code","airport_name","city","coordinates","timezone")\n' +
    'VALUES (@C0,@C1,@C2,geometry::STGeomFromWKB(@C3,4326),@C4)'
}
```

**Comment by markddrake** [comment]
There was a missing 'break' statement in the switch used to define the inputs to the operation. The break has been added.
