### ISSUE TITLE
PostgresDBI: NULL exception when exporting unqualified INTERVAL data types.

### ISSUE THREAD

**Issue by markddrake** [markddrake/YADAMU---Yet-Another-DAta-Migration-Utility#64]
```
2021-02-10T22:19:43.094Z [ERROR][PIPELINE][WRITER0][Postgres][FILE]["standard_data_types"][table][FLUSH][Manager]: Cannot read property 'split' of null
TypeError: Cannot read property 'split' of null
    at Function.decomposeDataType (C:\Development\YADAMU\src\YADAMU\common\yadamuLibrary.js:172:37)
    at C:\Development\YADAMU\src\YADAMU\file\node\jsonWriter.js:25:38
    at Array.map (<anonymous>)
    at JSONWriter.setTableInfo (C:\Development\YADAMU\src\YADAMU\file\node\jsonWriter.js:24:59)
    at JSONWriter.initialize (C:\Development\YADAMU\src\YADAMU\common\yadamuWriter.js:102:10)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async JSONWriter.initialize (C:\Development\YADAMU\src\YADAMU\file\node\jsonWriter.js:133:2)
    at async JSONWriter._write (C:\Development\YADAMU\src\YADAMU\common\yadamuWriter.js:482:8)
```

This error occurs when a table contains an unrestricted INTERVAL data_type.

**Comment by markddrake** [comment]
Problem occurs when a table contains column of type INTERVAL and the INTERVAL_TYPE column in  the INFORMATION_SCHEMA.COLUMNS row corresponding the column does not contain any additional info. This condition is now checked for and handled correctly.
