### ISSUE TITLE
Add correct default values for length and scale when binding numeric and decimal data types and explicit values are not provided.

### ISSUE THREAD

**Issue by markddrake** [markddrake/YADAMU---Yet-Another-DAta-Migration-Utility#72]
The MsSQL Driver was using incorrect default values for length and scale when Binding Numeric and Decimal data types when the table metadata not provide explicit length and scale values. This let to BCP issues when loading data which in term caused node to terminate. 

```
internal/buffer.js:735
    throw new ERR_OUT_OF_RANGE('value', `>= ${min} and <= ${max}`, value);
    ^

RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 255. Received 65535
    at writeU_Int8 (internal/buffer.js:735:11)
    at Buffer.writeUInt8 (internal/buffer.js:745:10)
    at WritableTrackingBuffer.writeUInt8 (C:\Development\YADAMU\src\node_modules\tedious\lib\tracking-buffer\writable-tracking-buffer.js:77:17)
    at Object.writeTypeInfo (C:\Development\YADAMU\src\node_modules\tedious\lib\data-types\numeric.js:48:12)
    at BulkLoad.getColMetaData (C:\Development\YADAMU\src\node_modules\tedious\lib\bulk-load.js:274:14)
    at RowTransform._transform (C:\Development\YADAMU\src\node_modules\tedious\lib\bulk-load.js:368:31)
    at RowTransform.Transform._read (C:\Development\YADAMU\src\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:177:10)
    at RowTransform.Transform._write (C:\Development\YADAMU\src\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:164:83)
    at doWrite (C:\Development\YADAMU\src\node_modules\tedious\node_modules\readable-stream\lib\_stream_writable.js:409:139)
    at writeOrBuffer (C:\Development\YADAMU\src\node_modules\tedious\node_modules\readable-stream\lib\_stream_writable.js:398:5) {
  code: 'ERR_OUT_OF_RANGE'
}
```

**Comment by markddrake** [comment]
Correct values are not supplied when explicit values are not provided by the metadata.

Note the BCP error caused the node process to abort, and it did not appear to be possible to 'catch' and handle this error.
