### ISSUE TITLE
Copy operation fails with:  this.yadamu.reloadParameters is not a function

### ISSUE THREAD

**Issue by markddrake** [markddrake/YADAMU---Yet-Another-DAta-Migration-Utility#73]
The stack trace is 
```
C:\Development\YADAMU>bin\copy config=qa\YDB1\sampleJob#1.json
TypeError: this.yadamu.reloadParameters is not a function
    at Copy.doCopy (C:\Development\YADAMU\src\YADAMU\common\yadamuCLI.js:461:19)
    at main (C:\Development\YADAMU\src\YADAMU\common\copy.js:12:24)
    at Object.<anonymous> (C:\Development\YADAMU\src\YADAMU\common\copy.js:23:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by markddrake** [comment]
function reloadParameters() has been restored to Yadamu.js
