### ISSUE TITLE
Unload fails with TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by markddrake** [markddrake/YADAMU---Yet-Another-DAta-Migration-Utility#75]
```
2021-02-18T16:30:39.583Z [INFO][YADAMU][EXPORT]: Operation complete: File:"HR.json". Elapsed Time: 00:00:00.046s.
root@8051f32ec26d:/usr/src/YADAMU# bin/unload.sh rdbms=oracle userid=system/oracle@//ORA1903-01:1521/PDB19300 OUTPUT_FORMAT=CSV FROM_USER=HR
TypeError: Cannot read property 'includes' of undefined
    at Yadamu.isSupportedValue (/usr/src/YADAMU/src/YADAMU/common/yadamu.js:263:22)
    at /usr/src/YADAMU/src/YADAMU/common/yadamu.js:531:45
    at Array.forEach (<anonymous>)
    at Yadamu.readCommandLineParameters (/usr/src/YADAMU/src/YADAMU/common/yadamu.js:343:18)
    at Yadamu.get COMMAND_LINE_PARAMETERS [as COMMAND_LINE_PARAMETERS] (/usr/src/YADAMU/src/YADAMU/common/yadamu.js:74:75)
    at Yadamu.initializeParameters (/usr/src/YADAMU/src/YADAMU/common/yadamu.js:185:40)
    at new Yadamu (/usr/src/YADAMU/src/YADAMU/common/yadamu.js:147:10)
    at new YadamuCLI (/usr/src/YADAMU/src/YADAMU/common/yadamuCLI.js:159:19)
    at new Unload (/usr/src/YADAMU/src/YADAMU/common/unload.js:5:1)
    at main (/usr/src/YADAMU/src/YADAMU/common/unload.js:10:26)
```

**Comment by markddrake** [comment]
This was causes by inconsistent naming of the constant that contains the list of valid values for parameter OUTPUT_FORMAT. This has now been fixed.

```
C:\Development\YADAMU>bin\unload rdbms=oracle userid=system/oracle@YDB11903 OUTPUT_FORMAT=CSV FROM_USER=HR TO_USER=HR
2021-02-19T03:39:24.377Z[WARNING][OracleDBI]: Suppling a password on the command line interface can be insecure
2021-02-19T03:39:24.756Z [INFO][Oracle][19][Configuration]: JSON storage model is BLOB.
2021-02-19T03:39:24.756Z [INFO][Reader][Oracle][19][DATA_ONLY][Manager]: Ready.
2021-02-19T03:39:24.770Z [INFO][Writer][LOADER][N/A][DATA_ONLY][Manager]: Ready.
2021-02-19T03:39:24.795Z [INFO][Import][LOADER]: Created control file "HR\HR.json"
2021-02-19T03:39:24.995Z [DDL][Oracle]: Generated metadata for 7 tables. Elapsed time: 00:00:00.127s.
2021-02-19T03:39:25.001Z [INFO][PIPELINE][SEQUENTIAL][Oracle][LOADER]: Processing 7 Tables
2021-02-19T03:39:25.031Z [DDL][LOADER]: Generated no "Create Table" statements and no DML statements. Elapsed time: 00:00:00.034s.
2021-02-19T03:39:25.052Z [DDL][LOADER]: Executed 0 DDL operations. Elapsed time: 00:00:00.000s.
2021-02-19T03:39:25.067Z [INFO][JOBS][JSON]: Rows 19. Reader Elapsed Time: 00:00:00.037s. Throughput 507 rows/s.  Writer Elapsed Time: 00:00:00.011s. SQL Exection Time: 00:00:00.000s. Throughput: 1622 rows/s.
2021-02-19T03:39:25.081Z [INFO][REGIONS][JSON]: Rows 4. Reader Elapsed Time: 00:00:00.002s. Throughput 1373 rows/s.  Writer Elapsed Time: 00:00:00.009s. SQL Exection Time: 00:00:00.000s. Throughput: 421 rows/s.
2021-02-19T03:39:25.110Z [INFO][COUNTRIES][JSON]: Rows 25. Reader Elapsed Time: 00:00:00.006s. Throughput 3758 rows/s.  Writer Elapsed Time: 00:00:00.024s. SQL Exection Time: 00:00:00.000s. Throughput: 1006 rows/s.
2021-02-19T03:39:25.141Z [INFO][EMPLOYEES][JSON]: Rows 107. Reader Elapsed Time: 00:00:00.022s. Throughput 4727 rows/s.  Writer Elapsed Time: 00:00:00.028s. SQL Exection Time: 00:00:00.000s. Throughput: 3715 rows/s.
2021-02-19T03:39:25.157Z [INFO][LOCATIONS][JSON]: Rows 23. Reader Elapsed Time: 00:00:00.003s. Throughput 6654 rows/s.  Writer Elapsed Time: 00:00:00.013s. SQL Exection Time: 00:00:00.000s. Throughput: 1706 rows/s.
2021-02-19T03:39:25.177Z [INFO][DEPARTMENTS][JSON]: Rows 27. Reader Elapsed Time: 00:00:00.003s. Throughput 6876 rows/s.  Writer Elapsed Time: 00:00:00.008s. SQL Exection Time: 00:00:00.000s. Throughput: 3070 rows/s.
2021-02-19T03:39:25.207Z [INFO][JOB_HISTORY][JSON]: Rows 10. Reader Elapsed Time: 00:00:00.002s. Throughput 4235 rows/s.  Writer Elapsed Time: 00:00:00.014s. SQL Exection Time: 00:00:00.000s. Throughput: 690 rows/s.
2021-02-19T03:39:25.242Z [INFO][YADAMU][UNLOAD]: Operation completed successfully. Elapsed time: 00:00:00.943.
2021-02-19T03:39:25.245Z [INFO][YADAMU][UNLOAD]: Operation complete: Control File:"HR\HR.json". Elapsed Time: 00:00:00.860s.

C:\Development\YADAMU>dir /s HR
 Volume in drive C is Local Disk
 Volume Serial Number is 16DE-2F50

 Directory of C:\Development\YADAMU\HR

02/19/2021  03:39 AM    <DIR>          .
02/19/2021  03:39 AM    <DIR>          ..
02/19/2021  03:39 AM    <DIR>          data
02/19/2021  03:39 AM             2,115 HR.json
02/19/2021  03:39 AM    <DIR>          metadata
               1 File(s)          2,115 bytes

 Directory of C:\Development\YADAMU\HR\data

02/19/2021  03:39 AM    <DIR>          .
02/19/2021  03:39 AM    <DIR>          ..
02/19/2021  03:39 AM               523 COUNTRIES.csv
02/19/2021  03:39 AM               883 DEPARTMENTS.csv
02/19/2021  03:39 AM            11,554 EMPLOYEES.csv
02/19/2021  03:39 AM               881 JOBS.csv
02/19/2021  03:39 AM               686 JOB_HISTORY.csv
02/19/2021  03:39 AM             1,496 LOCATIONS.csv
02/19/2021  03:39 AM                72 REGIONS.csv
               7 File(s)         16,095 bytes

 Directory of C:\Development\YADAMU\HR\metadata

02/19/2021  03:39 AM    <DIR>          .
02/19/2021  03:39 AM    <DIR>          ..
02/19/2021  03:39 AM               237 COUNTRIES.json
02/19/2021  03:39 AM               285 DEPARTMENTS.json
02/19/2021  03:39 AM               533 EMPLOYEES.json
02/19/2021  03:39 AM               269 JOBS.json
02/19/2021  03:39 AM               299 JOB_HISTORY.json
02/19/2021  03:39 AM               359 LOCATIONS.json
02/19/2021  03:39 AM               203 REGIONS.json
               7 File(s)          2,185 bytes

     Total Files Listed:
              15 File(s)         20,395 bytes
               8 Dir(s)  278,702,653,440 bytes free

C:\Development\YADAMU>
C:\Development\YADAMU>type HR\data\COUNTRIES.csv
"AR","Argentina","2"
"AU","Australia","3"
"BE","Belgium","1"
"BR","Brazil","2"
"CA","Canada","2"
"CH","Switzerland","1"
"CN","China","3"
"DE","Germany","1"
"DK","Denmark","1"
"EG","Egypt","4"
"FR","France","1"
"IL","Israel","4"
"IN","India","3"
"IT","Italy","1"
"JP","Japan","3"
"KW","Kuwait","4"
"ML","Malaysia","3"
"MX","Mexico","2"
"NG","Nigeria","4"
"NL","Netherlands","1"
"SG","Singapore","3"
"UK","United Kingdom","1"
"US","United States of America","2"
"ZM","Zambia","4"
"ZW","Zimbabwe","4"
```
