### ISSUE TITLE
Snowflake inserts fail when Floating Point numbers contain Infinity, -Infinity and NaN

### ISSUE THREAD

**Issue by markddrake** [markddrake/YADAMU---Yet-Another-DAta-Migration-Utility#82]
Insert into Snowflake fail when an attempt is made to insert the values Infinity, -Infinity or NaN into floating point column 

The root cause is 
```
   cause: Error [OperationFailedError]: Numeric value 'null' is not recognized
       at createError (C:\Development\YADAMU\src\node_modules\snowflake-sdk\lib\errors.js:525:15)
       at Object.exports.createOperationFailedError (C:\Development\YADAMU\src\node_modules\snowflake-sdk\lib\errors.js:304:10)
       at Object.callback (C:\Development\YADAMU\src\node_modules\snowflake-sdk\lib\services\sf.js:624:28)
       at Request._callback (C:\Development\YADAMU\src\node_modules\snowflake-sdk\lib\http\base.js:107:19)
       at Request.self.callback (C:\Development\YADAMU\src\node_modules\request\request.js:185:22)
       at Request.emit (events.js:315:20)
       at Request.<anonymous> (C:\Development\YADAMU\src\node_modules\request\request.js:1154:10)
       at Request.emit (events.js:315:20)
       at IncomingMessage.<anonymous> (C:\Development\YADAMU\src\node_modules\request\request.js:1076:12)
       at Object.onceWrapper (events.js:421:28) {
     code: '100038',
     sqlState: '22018',
     data: {
       internalError: false,
       errorCode: '100038',
       age: 0,
       sqlState: '22018',
       queryId: '019a905d-0463-8352-000d-5483005303ee'
     }
```

**Comment by markddrake** [comment]
Snowflake expects the String 'Inf', '-Inf' and 'Nan', rather then a Floating point value containing the value Infinity, -Infinity and Nan. In my mind this is a bug in the snowflake-sdk

Code has been added the Yadamu Snowflake driver to scan incoming floating point values and perform the necessary conversions to allow the insert to succeed. Also be aware that (at least with Number as String option) the value NULL is returned as the string 'NULL'. Again code has been added to work around this 'feature' of the snowflake-sdk module
